resolver: nightly-2021-07-04 # GHC 9.0.1

packages:
- '.'

extra-deps:
- archive: https://github.com/llvm-hs/llvm-hs/archive/refs/heads/llvm-12.zip
  subdirs:
  - llvm-hs
  - llvm-hs-pure

flags:
  llvm-hs:
    shared-llvm: true
    llvm-with-rtti: false

ghc-options:
  llvm-hs: -optcxx=-std=c++14 -optcxx=-lstdc++ -optcxx=-fno-rtti
