resolver: lts-16.31

# Use snapshot.yaml when testing locally against an unreleased llvm-hs version
#resolver: snapshot.yaml

packages:
- '.'

# Comment extra-deps out when running tests against snapshot.yaml
extra-deps:
- llvm-hs-12.0.0
- llvm-hs-pure-12.0.0

flags:
  llvm-hs:
    shared-llvm: true

